### PR TITLE
Devise with Meetup

### PR DESCRIPTION
**Pull request by berkcaputcu**
This should be working properly.
After first sign in, it asks for the email to complete the registration. After that, user automatically gets signed in.

I think the end of line characters caused a problem and that's why it looks like I changed everything on every file but obviously it's not the case. Sorry for the huge diff. I'll try to fix this but meanwhile you can use this pull request as a reference.

### CODE REVIEW

**Comment by fun-ruby** [comment]
Let's try and get the "false-positive" diffs removed. There's just too much noise to wade through...

**Comment by berkcaputcu** [comment]
Yeah, I tried removing them manually but apparently pull requests are commit based so I couldn't separate them.

**Comment by fun-ruby** [comment]
Since your fork is so new it may be worthwhile to delete it and fork another. You will want to keep your change-set of course.

Alternatively, it is possible to delete git commits. Here are some how-to links I found on stackoverlow that may help.

http://stackoverflow.com/questions/448919/how-can-i-remove-a-commit-on-github

http://stackoverflow.com/questions/1338728/how-to-delete-a-git-commit

**Comment by xander-miller** [comment]
We trying build without Devise for now. So I'm closing this PR.

**Pull request closed without merging**
